class TaskStatus(PermissionError): ...

class TaskCannotStart(TaskStatus): ...
class TaskCannotCompleted(TaskStatus): ...
class TaskCannotCancel(TaskStatus): ...

class TaskNotFind(Exception): ...


class ParsingError(ValueError):
    pass