[pytest]
pythonpath = .

addopts =
    -v
    -ra
    --strict-markers
    --cov-report=term-missing
    --cov-report=html

testpath = tests

markers =
    smoke: Дымовые тесты для критического функционала
    regression: Полный набор регрессионных тестов
    slow: Медленные тесты (например, с доступом к сети)
    api: Тесты, взаимодействующие с внешним API
    database: Тесты, требующие доступа к БД